# Generated by Django 2.1.5 on 2019-02-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['Title']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['Title']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='Artist',
        ),
        migrations.AddField(
            model_name='album',
            name='Released_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Composer',
            field=models.ManyToManyField(related_name='Composer', to='songs.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='Duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Singer',
            field=models.ManyToManyField(related_name='Singer', to='songs.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='Cast',
            field=models.ManyToManyField(to='songs.Actor'),
        ),
    ]
