# Generated by Django 2.1.5 on 2019-02-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20190209_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
