# Generated by Django 2.1.5 on 2019-02-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20190209_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
