# Generated by Django 2.1.5 on 2019-02-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='owner',
        ),
    ]
