# Generated by Django 2.1.5 on 2019-02-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_auto_20190209_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='Composer',
            field=models.ManyToManyField(blank=True, related_name='Composer', to='songs.Artist'),
        ),
    ]
