# Generated by Django 2.1.5 on 2019-02-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20190209_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='File',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
