# Generated by Django 2.1.5 on 2019-02-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='File',
        ),
    ]
