# Generated by Django 2.1.5 on 2019-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Composer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Singer',
        ),
        migrations.AddField(
            model_name='song',
            name='Artist',
            field=models.ManyToManyField(blank=True, null=True, to='songs.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='Released_on',
            field=models.DateField(blank=True, help_text='Format : YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='Title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
