# Generated by Django 2.1.5 on 2019-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_auto_20190217_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='default/profile.png', null=True, upload_to=''),
        ),
    ]
